In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('../../datasets/sales_practice.csv')

In [6]:
df.describe()

              value        sales
count   2134.000000  2157.000000
mean    8050.724461     2.917478
std    17842.820717     1.999456
min      135.000000    -8.000000
25%      779.000000     2.000000
50%     1486.000000     3.000000
75%     4297.750000     4.000000
max    88930.000000    11.000000

In [7]:
df.isnull()

       date  category  value  product  sales  region
0     False     False  False    False  False   False
1     False     False  False    False  False   False
2     False     False  False    False  False   False
3     False     False  False    False  False   False
4     False     False  False    False   True   False
...     ...       ...    ...      ...    ...     ...
2220  False     False  False    False  False   False
2221  False     False  False    False  False   False
2222  False     False  False    False  False   False
2223  False     False  False    False  False   False
2224  False     False  False    False  False   False

[2225 rows x 6 columns]

In [8]:
df.isnull().sum()

date         0
category     0
value       91
product     35
sales       68
region      45
dtype: int64

In [9]:
df.isnull().any(axis=0)

date        False
category    False
value        True
product      True
sales        True
region       True
dtype: bool

In [10]:
# filling the missing values with the 0 using fillna 
df_filled = df.fillna(0)

df_filled.isnull().sum()

C:\Users\saik3\AppData\Local\Temp\ipykernel_4180\1390790388.py:2: Pandas4Warning: 'int' is not supported as a fill value for str dtype. In a future version, calling fillna with an incompatible value will raise. Explicitly cast to a common dtype before filling.
  df_filled = df.fillna(0)

date        0
category    0
value       0
product     0
sales       0
region      0
dtype: int64

In [11]:
#filling the missing value with the mean of the column 

df['sales_fillna']= df['sales'].fillna(df['sales'].mean())
df

,date,category,value,product,sales,region,sales_fillna
0,2023-03-29,Books,338.0,Biography,2.0,South,2.000000
1,2023-06-22,Grocery,552.0,Toor Dal,1.0,South,1.000000
2,2025-04-16,Electronics,60988.0,Bluetooth Speaker,3.0,West,3.000000
3,2025-08-14,Home & Kitchen,9475.0,Mixer Grinder,1.0,East,1.000000
4,2024-10-31,Toys,3664.0,Doll,NaN,North,2.917478
...,...,...,...,...,...,...,...
2220,2025-09-23,Beauty,1368.0,Sunscreen,3.0,South,3.000000
2221,2023-03-12,Books,1258.0,Self-Help,2.0,South,2.000000
2222,2024-01-07,Apparel,965.0,Saree,6.0,South,6.000000
2223,2024-09-24,Apparel,1146.0,Saree,1.0,West,1.000000
2224,2023-02-22,Sports,843.0,Cycling Helmet,2.0,North-East,2.000000

In [12]:
#renaming the column names 
df = df.rename(columns={'date':'sales date'})
df.head()

,sales date,category,value,product,sales,region,sales_fillna
0,2023-03-29,Books,338.0,Biography,2.0,South,2.000000
1,2023-06-22,Grocery,552.0,Toor Dal,1.0,South,1.000000
2,2025-04-16,Electronics,60988.0,Bluetooth Speaker,3.0,West,3.000000
3,2025-08-14,Home & Kitchen,9475.0,Mixer Grinder,1.0,East,1.000000
4,2024-10-31,Toys,3664.0,Doll,NaN,North,2.917478

In [ ]:
#finding the data type of the columns 

df.dtypes

sales date          str
category            str
value           float64
product             str
sales           float64
region              str
sales_fillna    float64
dtype: object