In [1]:
import pandas as pd

In [27]:
df = pd.read_csv('../../datasets/sales_practice.csv')

In [28]:
df.describe()

              value        sales
count   2134.000000  2157.000000
mean    8050.724461     2.917478
std    17842.820717     1.999456
min      135.000000    -8.000000
25%      779.000000     2.000000
50%     1486.000000     3.000000
75%     4297.750000     4.000000
max    88930.000000    11.000000

In [29]:
df.isnull()

       date  category  value  product  sales  region
0     False     False  False    False  False   False
1     False     False  False    False  False   False
2     False     False  False    False  False   False
3     False     False  False    False  False   False
4     False     False  False    False   True   False
...     ...       ...    ...      ...    ...     ...
2220  False     False  False    False  False   False
2221  False     False  False    False  False   False
2222  False     False  False    False  False   False
2223  False     False  False    False  False   False
2224  False     False  False    False  False   False

[2225 rows x 6 columns]

In [30]:
df.isnull().sum()

date         0
category     0
value       91
product     35
sales       68
region      45
dtype: int64

In [31]:
df.isnull().any(axis=0)

date        False
category    False
value        True
product      True
sales        True
region       True
dtype: bool

In [32]:
# filling the missing values with the 0 using fillna 
df_filled = df.fillna(0)

df_filled.isnull().sum()

C:\Users\saik3\AppData\Local\Temp\ipykernel_11732\1390790388.py:2: Pandas4Warning: 'int' is not supported as a fill value for str dtype. In a future version, calling fillna with an incompatible value will raise. Explicitly cast to a common dtype before filling.
  df_filled = df.fillna(0)

date        0
category    0
value       0
product     0
sales       0
region      0
dtype: int64

In [33]:
#filling the missing value with the mean of the column 

df['sales_fillna']= df['sales'].fillna(df['sales'].mean())
df

,date,category,value,product,sales,region,sales_fillna
0,2023-03-29,Books,338.0,Biography,2.0,South,2.000000
1,2023-06-22,Grocery,552.0,Toor Dal,1.0,South,1.000000
2,2025-04-16,Electronics,60988.0,Bluetooth Speaker,3.0,West,3.000000
3,2025-08-14,Home & Kitchen,9475.0,Mixer Grinder,1.0,East,1.000000
4,2024-10-31,Toys,3664.0,Doll,NaN,North,2.917478
...,...,...,...,...,...,...,...
2220,2025-09-23,Beauty,1368.0,Sunscreen,3.0,South,3.000000
2221,2023-03-12,Books,1258.0,Self-Help,2.0,South,2.000000
2222,2024-01-07,Apparel,965.0,Saree,6.0,South,6.000000
2223,2024-09-24,Apparel,1146.0,Saree,1.0,West,1.000000
2224,2023-02-22,Sports,843.0,Cycling Helmet,2.0,North-East,2.000000

In [38]:
df.isnull().sum()

sales date       0
category         0
value           91
product         35
sales            0
region          45
sales_fillna     0
dtype: int64

In [39]:
#renaming the column names 
df = df.rename(columns={'date':'sales date'})
df.head()

,sales date,category,value,product,sales,region,sales_fillna
0,2023-03-29,Books,338.0,Biography,2,South,2.000000
1,2023-06-22,Grocery,552.0,Toor Dal,1,South,1.000000
2,2025-04-16,Electronics,60988.0,Bluetooth Speaker,3,West,3.000000
3,2025-08-14,Home & Kitchen,9475.0,Mixer Grinder,1,East,1.000000
4,2024-10-31,Toys,3664.0,Doll,2,North,2.917478

In [40]:
#finding the data type of the columns 

df.dtypes

sales date          str
category            str
value           float64
product             str
sales             int64
region              str
sales_fillna    float64
dtype: object

In [41]:
#changing the data type of the column 

df['sales'] =df['sales'].fillna(df['sales'].mean()).astype(int)
df.head()

,sales date,category,value,product,sales,region,sales_fillna
0,2023-03-29,Books,338.0,Biography,2,South,2.000000
1,2023-06-22,Grocery,552.0,Toor Dal,1,South,1.000000
2,2025-04-16,Electronics,60988.0,Bluetooth Speaker,3,West,3.000000
3,2025-08-14,Home & Kitchen,9475.0,Mixer Grinder,1,East,1.000000
4,2024-10-31,Toys,3664.0,Doll,2,North,2.917478

In [42]:
df.dtypes

sales date          str
category            str
value           float64
product             str
sales             int64
region              str
sales_fillna    float64
dtype: object

In [43]:
# apply method ( apply method lets you apply the function to your data ) 

df['new_value']=df['value'].apply(lambda x:x*2)
df

,sales date,category,value,product,sales,region,sales_fillna,new_value
0,2023-03-29,Books,338.0,Biography,2,South,2.000000,676.0
1,2023-06-22,Grocery,552.0,Toor Dal,1,South,1.000000,1104.0
2,2025-04-16,Electronics,60988.0,Bluetooth Speaker,3,West,3.000000,121976.0
3,2025-08-14,Home & Kitchen,9475.0,Mixer Grinder,1,East,1.000000,18950.0
4,2024-10-31,Toys,3664.0,Doll,2,North,2.917478,7328.0
...,...,...,...,...,...,...,...,...
2220,2025-09-23,Beauty,1368.0,Sunscreen,3,South,3.000000,2736.0
2221,2023-03-12,Books,1258.0,Self-Help,2,South,2.000000,2516.0
2222,2024-01-07,Apparel,965.0,Saree,6,South,6.000000,1930.0
2223,2024-09-24,Apparel,1146.0,Saree,1,West,1.000000,2292.0
2224,2023-02-22,Sports,843.0,Cycling Helmet,2,North-East,2.000000,1686.0

In [44]:
# data aggregation and grouping 

df.head()

,sales date,category,value,product,sales,region,sales_fillna,new_value
0,2023-03-29,Books,338.0,Biography,2,South,2.000000,676.0
1,2023-06-22,Grocery,552.0,Toor Dal,1,South,1.000000,1104.0
2,2025-04-16,Electronics,60988.0,Bluetooth Speaker,3,West,3.000000,121976.0
3,2025-08-14,Home & Kitchen,9475.0,Mixer Grinder,1,East,1.000000,18950.0
4,2024-10-31,Toys,3664.0,Doll,2,North,2.917478,7328.0

In [45]:
# group by 

groupd_mean = df.groupby('product')['value'].mean()
print(groupd_mean)

product
Action Figure         3160.176471
Atta                   738.238095
Badminton Racket       983.302326
Basmati Rice           690.633333
Bedsheet              6366.228571
Biography              332.675000
Biscuits               151.255319
Bluetooth Speaker    60894.870968
Board Game            1688.641509
Body Lotion           1068.822222
Building Blocks       2576.607843
Comic                 1008.704545
Cookbook              1194.444444
Cookware Set          4694.764706
Cricket Bat           3863.843137
Cycling Helmet         756.076923
Doll                  3491.224490
Dumbbell Set          7460.818182
Earbuds              39591.423077
Face Wash             1462.731707
Football              4666.739130
Jacket                 664.631579
Jeans                 2935.500000
Kurta                 4006.872340
Laptop               71632.000000
Lip Balm               815.975000
Mixer Grinder        10513.285714
Novel                 1326.913043
Perfume                871.902439
Power Bank           80546.479167
Pressure Cooker       5765.421053
Puzzle                1378.948718
RC Car                 434.444444
Saree                 1060.666667
Self-Help             1293.500000
Shampoo               1236.707317
Smartphone            9523.512821
Smartwatch           40447.555556
Sneakers              2296.730769
Sunflower Oil          714.666667
Sunscreen             1562.468085
T-Shirt                636.982143
Table Fan             2550.900000
Tea Powder             661.404255
Textbook               498.064516
Toor Dal               490.521739
Water Bottle         11408.613636
Yoga Mat              2074.027778
Name: value, dtype: float64

In [46]:
# group by ( multiple columns )
grouped_sum = df.groupby(['product','region'])['value'].sum()
print(grouped_sum)

product        region
Action Figure   East          3128.0
               Central        3035.0
               East          16762.0
               North         28183.0
               South         28399.0
                              ...
Yoga Mat       East          12141.0
               North         14587.0
               North-East     1842.0
               South         16479.0
               West          16959.0
Name: value, Length: 329, dtype: float64

In [47]:
grouped_multiple_mean = df.groupby(['product','region'])['value'].mean()
print(grouped_multiple_mean)

product        region
Action Figure   East         3128.000000
               Central       3035.000000
               East          3352.400000
               North         3131.444444
               South         3155.444444
                                ...
Yoga Mat       East          2023.500000
               North         2083.857143
               North-East    1842.000000
               South         2059.875000
               West          2119.875000
Name: value, Length: 329, dtype: float64

In [48]:
# aggregate method 
grouped_agg = df.groupby('region')['value'].agg(['mean','sum','count'])
print(grouped_agg)

                     mean        sum  count
region
 Central      1468.000000     2936.0      2
 East         8883.461538   115485.0     13
 North        3904.714286    27333.0      7
 North-East   2503.666667     7511.0      3
 South        8926.363636    98190.0     11
 West         2675.800000    26758.0     10
Central       9050.393064  1565718.0    173
East          9669.525424  2852510.0    295
North         7871.990421  4109179.0    522
North-East    7745.349398   642864.0     83
South         7633.744275  4000082.0    524
West          7856.483296  3527561.0    449

In [50]:
df['valuefillna']=df['value'].fillna(df['value'].mean())
df

,sales date,category,value,product,sales,region,sales_fillna,new_value,valuefillna
0,2023-03-29,Books,338.0,Biography,2,South,2.000000,676.0,338.0
1,2023-06-22,Grocery,552.0,Toor Dal,1,South,1.000000,1104.0,552.0
2,2025-04-16,Electronics,60988.0,Bluetooth Speaker,3,West,3.000000,121976.0,60988.0
3,2025-08-14,Home & Kitchen,9475.0,Mixer Grinder,1,East,1.000000,18950.0,9475.0
4,2024-10-31,Toys,3664.0,Doll,2,North,2.917478,7328.0,3664.0
...,...,...,...,...,...,...,...,...,...
2220,2025-09-23,Beauty,1368.0,Sunscreen,3,South,3.000000,2736.0,1368.0
2221,2023-03-12,Books,1258.0,Self-Help,2,South,2.000000,2516.0,1258.0
2222,2024-01-07,Apparel,965.0,Saree,6,South,6.000000,1930.0,965.0
2223,2024-09-24,Apparel,1146.0,Saree,1,West,1.000000,2292.0,1146.0
2224,2023-02-22,Sports,843.0,Cycling Helmet,2,North-East,2.000000,1686.0,843.0

In [51]:
df.isnull().sum()

sales date       0
category         0
value           91
product         35
sales            0
region          45
sales_fillna     0
new_value       91
valuefillna      0
dtype: int64

In [52]:
df['revenue'] =df['sales_fillna']*df['valuefillna']
df

,sales date,category,value,product,sales,region,sales_fillna,new_value,valuefillna,revenue
0,2023-03-29,Books,338.0,Biography,2,South,2.000000,676.0,338.0,676.000000
1,2023-06-22,Grocery,552.0,Toor Dal,1,South,1.000000,1104.0,552.0,552.000000
2,2025-04-16,Electronics,60988.0,Bluetooth Speaker,3,West,3.000000,121976.0,60988.0,182964.000000
3,2025-08-14,Home & Kitchen,9475.0,Mixer Grinder,1,East,1.000000,18950.0,9475.0,9475.000000
4,2024-10-31,Toys,3664.0,Doll,2,North,2.917478,7328.0,3664.0,10689.639314
...,...,...,...,...,...,...,...,...,...,...
2220,2025-09-23,Beauty,1368.0,Sunscreen,3,South,3.000000,2736.0,1368.0,4104.000000
2221,2023-03-12,Books,1258.0,Self-Help,2,South,2.000000,2516.0,1258.0,2516.000000
2222,2024-01-07,Apparel,965.0,Saree,6,South,6.000000,1930.0,965.0,5790.000000
2223,2024-09-24,Apparel,1146.0,Saree,1,West,1.000000,2292.0,1146.0,1146.000000
2224,2023-02-22,Sports,843.0,Cycling Helmet,2,North-East,2.000000,1686.0,843.0,1686.000000

In [53]:
df['revenue']= df['revenue'].astype(int)
df

,sales date,category,value,product,sales,region,sales_fillna,new_value,valuefillna,revenue
0,2023-03-29,Books,338.0,Biography,2,South,2.000000,676.0,338.0,676
1,2023-06-22,Grocery,552.0,Toor Dal,1,South,1.000000,1104.0,552.0,552
2,2025-04-16,Electronics,60988.0,Bluetooth Speaker,3,West,3.000000,121976.0,60988.0,182964
3,2025-08-14,Home & Kitchen,9475.0,Mixer Grinder,1,East,1.000000,18950.0,9475.0,9475
4,2024-10-31,Toys,3664.0,Doll,2,North,2.917478,7328.0,3664.0,10689
...,...,...,...,...,...,...,...,...,...,...
2220,2025-09-23,Beauty,1368.0,Sunscreen,3,South,3.000000,2736.0,1368.0,4104
2221,2023-03-12,Books,1258.0,Self-Help,2,South,2.000000,2516.0,1258.0,2516
2222,2024-01-07,Apparel,965.0,Saree,6,South,6.000000,1930.0,965.0,5790
2223,2024-09-24,Apparel,1146.0,Saree,1,West,1.000000,2292.0,1146.0,1146
2224,2023-02-22,Sports,843.0,Cycling Helmet,2,North-East,2.000000,1686.0,843.0,1686

In [56]:
# multiple aggregation 
# .groupby(column).agg(variable_name = ("column","function"))

multiple_aggregations_groupby = df.groupby('region').agg(revenue_sum = ("revenue","sum") ,average_value =("valuefillna","mean"), units_sum = ("sales","sum") , orders=("sales","count"))
print(multiple_aggregations_groupby)

              revenue_sum  average_value  units_sum  orders
region
 Central            32049    3662.241487          8       3
 East              232747    8772.429928         41      15
 North              76135    3904.714286         22       7
 North-East         21051    2503.666667          7       3
 South             124589    8926.363636         23      11
 West              111940    3164.429496         34      11
Central           4096363    9033.353258        515     176
East              7757704    9606.249816        868     307
North            13156688    7878.902788       1633     543
North-East        1918124    7756.002016        232      86
South            12929295    7652.006181       1505     548
West             12884270    7865.162157       1418     470

In [64]:
# merging and joining data frames 

df1 = pd.DataFrame({'key':['a','b','c'] , 'values':[1,2,3]} )
df2 = pd.DataFrame({'key':['A','B','D'] , 'values':[4,5,6]} )

In [65]:
df1

  key  values
0   a       1
1   b       2
2   c       3

In [66]:
df2

  key  values
0   A       4
1   B       5
2   D       6

In [67]:
pd.merge(df1,df2,on='key',how='inner')

Empty DataFrame
Columns: [key, values_x, values_y]
Index: []

In [68]:
pd.merge(df1,df2,on='key',how='outer')

  key  values_x  values_y
0   A       NaN       4.0
1   B       NaN       5.0
2   D       NaN       6.0
3   a       1.0       NaN
4   b       2.0       NaN
5   c       3.0       NaN

In [69]:
pd.merge(df1,df2,on='key',how='left')

  key  values_x  values_y
0   a         1       NaN
1   b         2       NaN
2   c         3       NaN

In [70]:
pd.merge(df1,df2,on='key',how='right')

  key  values_x  values_y
0   A       NaN         4
1   B       NaN         5
2   D       NaN         6

In [71]:
#example 2 ( merge )

df3 = pd.DataFrame({'key':['a','b','c'] , 'value':[1,2,3] })
df4 = pd.DataFrame({'key':['a','b','d'] , 'value':[4,5,6]})

In [72]:
df3

  key  value
0   a      1
1   b      2
2   c      3

In [73]:
df4

  key  value
0   a      4
1   b      5
2   d      6

In [74]:
pd.merge(df3,df4,on='key',how='inner')

  key  value_x  value_y
0   a        1        4
1   b        2        5

In [75]:
pd.merge(df3,df4,on='key',how='outer')

  key  value_x  value_y
0   a      1.0      4.0
1   b      2.0      5.0
2   c      3.0      NaN
3   d      NaN      6.0

In [76]:
pd.merge(df3,df4,on='key',how='left')

  key  value_x  value_y
0   a        1      4.0
1   b        2      5.0
2   c        3      NaN

In [77]:
pd.merge(df3,df4,on='key',how='right')

  key  value_x  value_y
0   a      1.0        4
1   b      2.0        5
2   d      NaN        6